### ISSUE TITLE
Unexpected error code in v2/blocks/{block_number}/data

### ISSUE THREAD

**Issue by ecioppettini** [availproject/avail-light#627]
Not really sure if this is intended or not, but it's slightly odd that the `v2/blocks/{block_number}/data` seems to return an error code of 400 (bad request) if there isn't any data for a block height _in_ the available range (for the particular app_id that the client is tracking).

For example, if I submit data at block 15, and query the endpoint with that block, I get a 200 (with the data). But if I request at 14 I get a Bad request. This seems odd, since bad request it's supposed to be a client error, but in this case you can't know if there is data or not in that block.

I think it's also inconsistent with the fact that if you ask for the data in a block in the future you get a 404 (not found), which is the case where I would think a bad request would make some sense (based on the docs).

The primary reason I care about this is because ideally I'd like to be able to discriminate on whether there is actually a problem with the request/light client (which is a problem), or just the fact that for that particular app_id there is no data there (which is not).

**Comment by aterentic-ethernal** [comment]
@ecioppettini , you are right that it is inconsistent, and the intention was to provide 200 OK only if data is available, and to force user to know that upfront, by either using websockets, or polling the `/v2/status` endpoint. 404 seems not useful here, and I also think both should be bad request, but feel free to discuss please. 

Also, described scenario sounds like a bug, and could be caused by introduction of empty blocks, so we will check if that is the case here.
